-- AB360WEB Seed Data (everything editable later from /admin)

INSERT OR REPLACE INTO settings (key,value) VALUES
('site_name','AB360WEB'),
('site_tagline','Your Business. Fully Online. Growing Daily.'),
('hero_title','We Grow Local Businesses Into Online Brands'),
('hero_sub','Ads, websites, WhatsApp marketing & AI automation — everything your business needs to get customers from the internet. Based in Muzaffarpur, serving all of India.'),
('hero_cta','Get Free Consultation'),
('logo_text','AB<span class="g">360</span>WEB'),
('phone','8700596736'),
('whatsapp','918700596736'),
('email','ab360web@gmail.com'),
('address','Muzaffarpur, Bihar, India'),
('map_link','https://maps.google.com/?q=Muzaffarpur,Bihar'),
('facebook',''),('instagram',''),('youtube',''),('linkedin',''),
('color_accent','#E8B84B'),
('color_bg','#0A0E1A'),
('color_surface','#101729'),
('seo_title','AB360WEB — Digital Marketing Agency in Muzaffarpur, Bihar'),
('seo_desc','Facebook & Google Ads, websites, WhatsApp marketing, e-commerce and AI solutions for local businesses. Get more customers online with AB360WEB.'),
('stat_years','10'),('stat_projects','40'),('stat_industries','12'),('stat_leadsgen','5000'),
('wa_welcome','Hi! I want to grow my business online. Please share details.'),
('sheet_webhook',''),
('callmebot_phone',''),('callmebot_key',''),
('popup_enabled','1'),
('popup_title','Want more customers this month?'),
('popup_text','Get a free 15-minute growth plan for your business. No charges, no conditions.');

INSERT OR REPLACE INTO automations (key,label,enabled,config) VALUES
('lead_to_sheet','Send every new lead to Google Sheet',0,'{}'),
('lead_wa_alert','WhatsApp alert to owner on new lead (CallMeBot - free)',0,'{}'),
('lead_autoreply_wa','Show WhatsApp thank-you link to visitor after form submit',1,'{}'),
('daily_summary','Daily lead summary on dashboard',1,'{}'),
('spam_protection','Spam protection on all forms (honeypot + rate limit)',1,'{}');

INSERT OR IGNORE INTO services (slug,title,tagline,icon,short_desc,description,includes,price_hint,sort) VALUES
('facebook-instagram-ads','Facebook & Instagram Ads','Get new customers every day','📣','Targeted ad campaigns that bring real enquiries, not just likes.','We plan, create and run Facebook & Instagram ad campaigns focused on one thing: getting you paying customers. Includes audience research, ad creatives, daily monitoring and monthly reporting.','["Campaign strategy & setup","Ad creatives (images + videos)","Audience targeting & retargeting","Click-to-WhatsApp campaigns","Monthly performance report"]','Starts ₹7,999/month + ad budget',1),
('google-ads','Google Ads','Appear on top when people search','🔍','Search, Maps and YouTube ads that capture ready-to-buy customers.','When someone searches for your service in your city, your business should appear first. We run Google Search, Maps and YouTube campaigns with proper keyword research and conversion tracking.','["Keyword research","Search & Maps campaigns","YouTube ads","Conversion tracking","Monthly report"]','Starts ₹7,999/month + ad budget',2),
('google-business-listing','Google Business & Maps Ranking','Your shop on Google Maps with 5-star reviews','📍','Get found by nearby customers searching on Google.','We set up, verify and optimise your Google Business Profile so you rank in local searches, manage your reviews, and turn searchers into walk-in customers.','["Profile setup & verification","Local SEO optimisation","Review management system","Photos & posts","Monthly ranking report"]','One-time ₹4,999 or ₹2,499/month',3),
('whatsapp-marketing','WhatsApp Marketing','Send offers to thousands of customers','💬','Bulk campaigns, chatbots and catalogs on the app everyone uses.','Reach all your customers where they actually are — WhatsApp. We set up broadcast campaigns, auto-reply chatbots and product catalogs that convert chats into orders.','["Bulk campaign setup","Auto-reply chatbot","WhatsApp catalog","Festival offer campaigns","Click-to-WhatsApp ads"]','Starts ₹5,999/month',4),
('website-booking','Website & Online Booking','Your business open online 24x7','🖥️','Fast, beautiful websites with booking and enquiry systems.','A premium website that builds trust and collects enquiries even while you sleep. Includes booking system, WhatsApp integration, and admin panel to manage everything yourself.','["Custom premium design","Mobile-first & fast loading","Booking / enquiry system","Admin panel (CMS)","Free hosting setup"]','Starts ₹14,999 one-time',5),
('ecommerce-store','Online Store (E-commerce)','Sell your products across India','🛒','Shopify / online store + Amazon, Flipkart & Meesho setup.','Take your products beyond your shop. We build your online store and set you up on Amazon, Flipkart and Meesho with payments, shipping and order management.','["Online store setup","Amazon / Flipkart / Meesho onboarding","Payment gateway & UPI","Product listing (up to 50)","Order management training"]','Starts ₹19,999 one-time',6),
('social-media-reels','Reels & Social Media Handling','Daily posting, handled by us','🎬','Content calendar, reels, festival creatives and full account management.','We manage your Instagram & Facebook completely — reels, posts, stories, festival creatives and captions — so your brand stays active and trending without you lifting a finger.','["12-20 posts/reels monthly","Festival & offer creatives","Captions & hashtags","Story updates","Monthly growth report"]','Starts ₹9,999/month',7),
('logo-branding','Logo & Branding','New business? Build your identity','🎨','Logo, visiting cards, brochures and complete brand kit.','First impressions matter. Get a professional logo and brand kit — colours, fonts, visiting card, letterhead and social media kit — that makes your business look established from day one.','["Logo (3 concepts)","Visiting card & letterhead","Social media kit","Brand colour & font guide","Brochure / menu design"]','Starts ₹3,999 one-time',8),
('ai-solutions','AI Solutions for Business','Chatbots, automation & smart tools','🤖','AI chatbots, auto follow-ups and content automation for your business.','Put AI to work in your business — chatbots that answer customers 24x7, automatic follow-ups so no lead is missed, and AI-generated content that saves hours every week.','["AI chatbot setup","Auto lead follow-up system","AI content generation setup","Business automation audit","Staff training included"]','Starts ₹9,999',9),
('custom-software','Custom Software & Apps','Software built for your exact business','⚙️','Billing, inventory, lab/school management systems and mobile apps.','Off-the-shelf software never fits perfectly. We build custom systems — billing, inventory, lab management, school management, booking apps — designed around how YOUR business actually works.','["Requirement study","Custom development","Admin dashboard","Staff training","3 months free support"]','Starts ₹29,999',10);

INSERT OR IGNORE INTO case_studies (slug,title,client,industry,challenge,solution,results,sort) VALUES
('lifeline-diagnostics','Pathlab Goes Digital: Online Bookings 24x7','LifeLine Diagnostics','Healthcare / Pathlab','Patients had to call or visit just to book a simple test. No online presence meant losing patients to bigger labs.','We built a complete website with online test booking, test catalog with prices, patient records and an admin panel the lab staff manage themselves — plus Google Business setup for local visibility.','[{"stat":"24x7","label":"Online booking enabled"},{"stat":"100+","label":"Tests listed online"},{"stat":"1st Page","label":"Google Maps visibility"}]',1),
('sprinkles-by-ruchi','Home Bakery Turned Online Brand','Sprinkles By Ruchi','Food / Bakery','A talented home bakery with zero online ordering system — all orders managed manually, limiting growth.','We built a premium online store with 16 product categories, WhatsApp-based ordering (no payment gateway fees), and a luxury brand look with custom fonts and styling.','[{"stat":"16","label":"Product categories online"},{"stat":"0%","label":"Payment gateway fees"},{"stat":"Premium","label":"Brand identity created"}]',2);

INSERT OR IGNORE INTO testimonials (name,business,text,rating,sort) VALUES
('Ruchi Sharma','Sprinkles By Ruchi, Muzaffarpur','My bakery finally looks as premium online as my cakes taste. Orders now come directly on WhatsApp — so simple for my customers.',5,1),
('Dr. A. Kumar','LifeLine Diagnostics','Patients book tests online even at midnight. The admin panel is so easy that my receptionist manages everything.',5,2),
('Rajesh Gupta','Local Retailer','I thought online marketing was only for big companies. My first Facebook campaign brought 30+ enquiries in a week.',5,3),
('Priya Singh','Coaching Institute','Admissions season was completely different this year — our WhatsApp was full of parent enquiries from the ads.',5,4);

INSERT OR IGNORE INTO faqs (question,answer,category,sort) VALUES
('How much budget do I need to start ads?','You can start meaningful Facebook/Google campaigns from ₹300-500 per day ad budget. We will suggest the right budget for your goal in the free consultation.','Ads',1),
('Do you work with businesses outside Muzaffarpur?','Yes. We serve clients across Bihar and all of India — everything is managed online with regular WhatsApp/call updates.','General',2),
('How will I know my ads are working?','You get a simple monthly report: how much was spent, how many people saw it, and most importantly how many enquiries/leads came. No confusing jargon.','Ads',3),
('Can I update the website myself after it is built?','Yes. Every website we build comes with a simple admin panel — change text, images, prices and offers yourself, no coding needed.','Websites',4),
('What if I do not get results?','We set clear expectations before starting. Marketing takes 2-4 weeks to optimise, and we share progress openly — you will always know exactly what is happening with your money.','General',5),
('Do you provide bills/invoices?','Yes, proper invoices are provided for all services.','General',6);

INSERT OR IGNORE INTO pages (slug,title,content) VALUES
('about','About AB360WEB','<h2>10+ Years of Tech. One Mission: Grow Local Businesses.</h2><p>AB360WEB is a digital growth agency based in Muzaffarpur, Bihar. We combine performance marketing, premium websites and AI automation to help local businesses get customers from the internet — without confusion, without jargon.</p><p>Our founder brings 10+ years of experience across AI, robotics and cybersecurity training, having conducted workshops in schools and colleges, plus hands-on experience running ads, building websites and managing online stores for real local businesses.</p><h3>Why businesses choose us</h3><ul><li><b>Local + Global:</b> We understand Bihar''s market AND world-class digital tools.</li><li><b>AI-Powered:</b> Automation and AI tools deliver big-agency quality at local prices.</li><li><b>Results-focused:</b> We talk in enquiries and customers, not vanity metrics.</li><li><b>Everything under one roof:</b> Ads, website, WhatsApp, branding, software — one team, one number.</li></ul>'),
('privacy','Privacy Policy','<p>AB360WEB ("we") respects your privacy. This policy explains what we collect and how we use it.</p><h3>What we collect</h3><p>When you submit a form we collect your name, phone, email and message to respond to your enquiry. We also collect anonymous page-visit statistics to improve our website.</p><h3>How we use it</h3><p>Only to contact you about your enquiry and provide our services. We never sell or share your data with third parties for marketing.</p><h3>Contact</h3><p>For any privacy concerns, contact us at ab360web@gmail.com.</p>'),
('terms','Terms & Conditions','<p>By using this website and our services you agree to these terms.</p><h3>Services</h3><p>Scope, timeline and pricing of every project are confirmed in writing (WhatsApp/email) before work begins. Work starts after the agreed advance payment.</p><h3>Payments</h3><p>Standard terms: 50% advance, 50% on completion. Monthly services are billed in advance. Ad budgets are paid directly to the platform (Meta/Google) by the client and are separate from our fees.</p><h3>Liability</h3><p>Marketing outcomes depend on many factors. We commit to professional execution and transparent reporting, not guaranteed sales figures.</p>'),
('refund','Refund Policy','<p>We believe in fair, transparent dealings.</p><h3>One-time projects</h3><p>If you cancel before work begins, the advance is refunded minus any costs already incurred (e.g. domain purchase). Once design/development work has started, the advance is non-refundable, but we will always complete the agreed scope.</p><h3>Monthly services</h3><p>Cancel anytime with 7 days notice before the next billing cycle. No refunds for the current month once campaigns/content work has started.</p><h3>Ad budgets</h3><p>Ad money is paid directly to Meta/Google and follows their policies. It does not pass through us.</p>'),
('careers','Careers at AB360WEB','<h2>Work With Us</h2><p>We are building Muzaffarpur''s most modern digital agency and occasionally look for talented people:</p><ul><li>Video editor / Reels creator</li><li>Meta & Google Ads executive</li><li>Field sales / client relationship executive</li></ul><p>Send your details and work samples on WhatsApp — we reply to everyone.</p>');

INSERT OR IGNORE INTO posts (slug,title,excerpt,content,category,tags) VALUES
('why-every-shop-needs-google-business','Why Every Shop in Bihar Needs a Google Business Profile (Free)','Customers search "near me" every day. If your shop is not on Google Maps, they find your competitor instead.','<p>Open Google and search "bakery near me" or "pathlab near me". The shops that appear on top are not lucky — they have an optimised <b>Google Business Profile</b>. And it is completely free.</p><h3>What it gets you</h3><ul><li>Your shop on Google Maps with directions</li><li>Customer reviews that build instant trust</li><li>Your timings, photos and offers visible to searchers</li><li>Direct calls and WhatsApp from the listing</li></ul><h3>The mistake most owners make</h3><p>They create the profile and forget it. No photos, no replies to reviews, wrong timings. Google ranks active, complete profiles higher.</p><p><b>Action step:</b> Add 10 real photos, reply to every review, and post one offer per week. Do this for 30 days and watch your calls increase.</p>','Local SEO','google,local seo,maps'),
('whatsapp-marketing-bihar-guide','WhatsApp Marketing: The #1 Sales Channel for Bihar Businesses','Email open rate: 20%. WhatsApp open rate: 95%+. Here is how smart local businesses are using it.','<p>In Bihar, customers may ignore emails and calls — but everyone checks WhatsApp. That is why WhatsApp is the highest-converting marketing channel for local businesses right now.</p><h3>3 ways to use it</h3><ol><li><b>Broadcast offers:</b> Festival offers, new stock alerts and reminders to your customer list.</li><li><b>Click-to-WhatsApp ads:</b> Facebook ads where one tap opens a chat with you — much better than forms.</li><li><b>Auto-reply chatbot:</b> Answers price/timing questions instantly, even at midnight.</li></ol><h3>One rule</h3><p>Never spam. Send value (offers, useful updates) maximum 2-4 times a month, and always to people who know your business.</p>','WhatsApp','whatsapp,marketing'),
('facebook-ads-mistakes-local-business','5 Facebook Ads Mistakes Local Businesses Make (And Easy Fixes)','Boosting posts randomly and getting only likes? You are making mistake #1.','<p>Most local businesses try Facebook ads once, waste money, and conclude "ads do not work". The truth: ads work — these mistakes do not.</p><h3>The 5 mistakes</h3><ol><li><b>Boosting posts</b> instead of running proper campaigns with objectives.</li><li><b>Targeting everyone</b> instead of your city + relevant interests.</li><li><b>No clear offer</b> — "We are the best" is not an offer. "Free home sample collection this week" is.</li><li><b>Sending clicks to nowhere</b> — always connect ads to WhatsApp or a landing page.</li><li><b>Judging in 2 days</b> — campaigns need 1-2 weeks of data to optimise.</li></ol><p><b>Fix one mistake this week</b> and your results will visibly improve.</p>','Ads','facebook ads,meta'),
('ai-tools-small-business','How Small Businesses Can Use AI Today (Without Big Budgets)','AI is not just for big companies. Here are practical ways a local shop can use it this month.','<p>AI sounds expensive and complicated. It is neither. Here is what local businesses are already doing:</p><ul><li><b>Customer replies:</b> AI chatbots answer "price kya hai?" and "timing?" instantly on WhatsApp.</li><li><b>Content:</b> Festival posts, captions and even ad copy generated in minutes.</li><li><b>Follow-ups:</b> Automatic reminders to leads who did not reply — no enquiry gets forgotten.</li><li><b>Photos:</b> AI product photoshoots — studio-quality images without a studio.</li></ul><p>The businesses adopting these tools now will look bigger, respond faster, and win more customers than competitors still doing everything manually.</p>','AI','ai,automation');
